package guis;

import entidades.Etiqueta;
import entidades.Hashtag;
import entidades.Publicacion;
import entidades.Usuario;
import helpers.ConvertirImagen;
import interfaces.IFachadaConexion;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import logica.FachadaConexion;

public class FrmEditarPublicacion extends javax.swing.JFrame {

    private IFachadaConexion fachadaConexion;
    private Publicacion publicacion;
    private JFileChooser jFile;
    private ImageIcon image;
    private Icon icon;
    private JLabel lblIcon;

    public FrmEditarPublicacion(Publicacion publicacion) {
        initComponents();
        this.fachadaConexion = new FachadaConexion();
        this.publicacion = publicacion;
        init();
    }

    private void init() {
        setImgUser();
        Usuario usuario = publicacion.getUsuario();
        txtTexto.setHintText("¿Qué estás pensando, " + usuario.getUsuario() + "?");
        txtTexto.setText(publicacion.getTexto());

        lblUsuario.setText(usuario.getUsuario());

        if (publicacion.getImagen() != null) {
            btnAgregarImagen.setText("Cambiar imagen");
        }

        lblIcon = new JLabel();
        lblIcon.setSize(334, 184);
        lblIcon.repaint();
    }

    private void setImgUser() {
        imgUser.setIcon(null);
        ImageIcon image = new ImageIcon("src/main/java/images/perfil.png");
        imgUser.setIcon(new ImageIcon(image.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPublicar = new javax.swing.JButton();
        btnAgregarImagen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new swingComponents.JIMSendTextPane();
        lblUsuario = new javax.swing.JLabel();
        imgUser = new javax.swing.JLabel();
        line1 = new swingComponents.Line();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Publicación");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        btnPublicar.setBackground(new java.awt.Color(0, 0, 0));
        btnPublicar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnPublicar.setForeground(new java.awt.Color(255, 255, 255));
        btnPublicar.setText("Editar");
        btnPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicarActionPerformed(evt);
            }
        });

        btnAgregarImagen.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarImagen.setText("Agregar imagen");
        btnAgregarImagen.setPreferredSize(new java.awt.Dimension(115, 25));
        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });

        txtTexto.setHintText("¿Qué estás pensando, Jorge?");
        jScrollPane1.setViewportView(txtTexto);

        lblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setText("Furcio");

        imgUser.setPreferredSize(new java.awt.Dimension(50, 50));

        line1.setForeground(new java.awt.Color(204, 204, 204));

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        lblTitulo.setText("Editar Publicación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(line1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsuario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(btnPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPublicar)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        this.jFile = new JFileChooser();
        int resultado = jFile.showOpenDialog(this);
        if (resultado != JFileChooser.CANCEL_OPTION) {
            File fileName = jFile.getSelectedFile();
            lblIcon.setIcon(null);
            this.image = new ImageIcon(fileName.getAbsolutePath());
            this.icon = new ImageIcon(this.image.getImage().getScaledInstance(lblIcon.getWidth(), lblIcon.getHeight(), Image.SCALE_DEFAULT));
            lblIcon.setIcon(this.icon);
            //this.visualizadorImagen(this.lblImagen, fileName.getAbsolutePath());
        }
    }//GEN-LAST:event_btnAgregarImagenActionPerformed

    private void btnPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicarActionPerformed
        if (icon != null) {
            Image image = ConvertirImagen.iconoAImagen(this.lblIcon.getIcon());
            byte[] bytes = ConvertirImagen.imagenABytes(image);
            publicacion.setTexto(txtTexto.getText().trim());
            publicacion.setImagen(bytes);
            publicacion.setHashtag(separarHashtags(txtTexto.getText()));
            publicacion.setEtiquetas(separarEtiquetas(txtTexto.getText()));
        } else {
            publicacion.setTexto(txtTexto.getText().trim());
            publicacion.setHashtag(separarHashtags(txtTexto.getText()));
            publicacion.setEtiquetas(separarEtiquetas(txtTexto.getText()));
        }
        fachadaConexion.editarPublicacion(publicacion);
        dispose();
    }//GEN-LAST:event_btnPublicarActionPerformed

    public List<Hashtag> separarHashtags(String text) {
        List<Hashtag> ht = new ArrayList();

        String[] filtro = text.split("#");
        String[] hashtags = new String[filtro.length - 1];
        for (int i = 1; i < filtro.length; i++) {
            ht.add(new Hashtag(filtro[i].split(" ")[0]));
        }
        for (int i = 0; i < hashtags.length; i++) {
            System.out.println(i + " " + hashtags[i]);
        }
        return ht;
    }

    public List<Etiqueta> separarEtiquetas(String text){
        List<Etiqueta> etiquetas = new ArrayList();
        
        String[] filtro = text.split("@");
        String[] hashtags = new String[filtro.length-1];
        for (int i=1;i<filtro.length; i++) {
            etiquetas.add(new Etiqueta(new Usuario(filtro[i].split(" ")[0])));
        }
        for (int i=0;i<hashtags.length; i++){
            System.out.println(i+ " "+ hashtags[i]);
        }
        return etiquetas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JButton btnPublicar;
    private javax.swing.JLabel imgUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private swingComponents.Line line1;
    private swingComponents.JIMSendTextPane txtTexto;
    // End of variables declaration//GEN-END:variables
}
