
package guis;

import components.NotificacionItem;
import entidades.Notificacion;
import entidades.Usuario;
import events.EventoConsultarNotificaciones;
import events.EventoRegistrarNotificacion;
import interfaces.IFachadaConexion;
import java.util.ArrayList;
import java.util.List;
import logica.Context;
import logica.FachadaConexion;
import observers.ObserverConsultarNotificaciones;
import observers.ObserverRegistrarNotificacion;
import peticiones.PeticionNotificacion;
import peticiones.PeticionNotificaciones;

/**
 *
 * @author Vastem
 */
public class FrmNotificaciones extends javax.swing.JFrame implements ObserverRegistrarNotificacion, ObserverConsultarNotificaciones {
    private List<Notificacion> notificaciones = new ArrayList();
    private IFachadaConexion fachadaConexion;
    private Usuario usuario;
    
    /**
     * Creates new form FrmNotificaciones
     */
    public FrmNotificaciones() {
        initComponents();
        fachadaConexion = new FachadaConexion();
        this.usuario = Context.getInstance().getUsuario();;
        EventoConsultarNotificaciones.getInstance().addObserver(this);
        EventoRegistrarNotificacion.getInstance().addObserver(this);
        consultarNotificaciones();
    }
    
    public void consultarNotificaciones(){
        fachadaConexion.consultarNotificaciones(this.usuario);
    }

    
    public void agregarNotificacion(Notificacion notificacion){
        panBody.agregarNotificacion(notificacion);
    }
    
    
    public void agregarNotificaciones(List<Notificacion> notificaciones){
        panBody.init(notificaciones);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        line1 = new swingComponents.Line();
        btnNotificacion = new javax.swing.JButton();
        panBody = new components.NotificacionesBody();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(233, 233, 233));

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        lblTitulo.setText("Notificaciones");

        line1.setForeground(new java.awt.Color(204, 204, 204));

        btnNotificacion.setText("Nueva notificación");
        btnNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(line1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lblTitulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(panBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotificacion)
                .addGap(18, 18, 18)
                .addComponent(panBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionActionPerformed
        FrmCrearNotificacion fNotificacion = new FrmCrearNotificacion();
        fNotificacion.setVisible(true);
        fNotificacion.toFront();
        fNotificacion.requestFocus();
    }//GEN-LAST:event_btnNotificacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNotificacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private swingComponents.Line line1;
    private components.NotificacionesBody panBody;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(PeticionNotificaciones peticion) {
        System.out.println("entro al eventop notificacion");
        agregarNotificaciones(peticion.getNotificaciones());
    }

    @Override
    public void update(PeticionNotificacion peticion) {
        agregarNotificacion(peticion.getNotificacion());
    }
}
