/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guis;

import components.MuroBody;
import components.MuroTitle;
import entidades.Publicacion;
import java.util.List;
import net.miginfocom.swing.MigLayout;

public class PMuro extends javax.swing.JPanel {
    
    public PMuro() {
        initComponents();
        
    }
    
    public void init(List<Publicacion> publicaciones){
        setLayout(new MigLayout("fillx", "0[fill]0", "0[shrink 0]0[87%]0"));
        MuroTitle muroTitulo= new MuroTitle();
        MuroBody muroBody = new MuroBody(publicaciones);
        
        add(muroTitulo,"wrap");
        add(muroBody,"wrap");
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
