package guis;

import components.Linea;
import components.MuroBody;
import components.MuroPublicar;
import components.MuroTitle;
import entidades.Comentario;
import entidades.Publicacion;
import java.awt.Color;
import java.util.List;
import net.miginfocom.swing.MigLayout;

public class PMuro extends javax.swing.JPanel {

    private MuroBody muroBody;

    public PMuro() {
        initComponents();
    }

    public void init(List<Publicacion> publicaciones) {
        removeAll();
        setLayout(new MigLayout("fillx", "0[]0[]0[]0[]0", "0[shrink 0]0[]5[]-10[77%, top]0"));
        MuroTitle muroTitulo = new MuroTitle();
        this.muroBody = new MuroBody(publicaciones);
        MuroPublicar muroPublicar = new MuroPublicar();
        Linea linea = new Linea(new Color(233, 233, 233));
        add(muroTitulo, "wrap, al center");
        add(linea, "wrap, width 100%");
        add(muroPublicar, "wrap, al center");
        add(muroBody, "width 100%");
    }

    private void refresh() {
        repaint();
        revalidate();
    }

    public void agregarPublicacion(Publicacion publicacion) {
        muroBody.agregarPublicacion(publicacion);
        refresh();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(233, 233, 233));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
