package guis;

import components.Linea;
import components.MuroBody;
import components.MuroPublicacion;
import components.MuroPublicar;
import components.MuroTitle;
import entidades.Publicacion;
import entidades.Usuario;
import java.util.List;
import net.miginfocom.swing.MigLayout;

public class PMuro extends javax.swing.JPanel {

    private Usuario usuario;
    private MuroBody muroBody;

    public PMuro(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }

    public void init(List<Publicacion> publicaciones) {
        setLayout(new MigLayout("fillx", "0[]0[]0[]0[]0", "0[shrink 0]0[]10[shrink 0]0[77%, top]0"));
        MuroTitle muroTitulo = new MuroTitle(usuario);
        this.muroBody = new MuroBody(publicaciones, usuario);
        MuroPublicar muroPublicar = new MuroPublicar(usuario);
        Linea linea = new Linea();
        add(muroTitulo, "wrap, al center");
        add(linea, "wrap, width 100%");
        add(muroPublicar, "wrap, al center");
        add(muroBody, "width 100%");
        repaint();
        revalidate();
    }

    public void agregarPublicacion(Publicacion publicacion) {
        muroBody.agregarPublicacion(publicacion);
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
