package guis;

import components.Linea;
import components.NotificacionesBody;
import components.MuroPublicar;
import components.MuroTitle;
import components.NotificacionItem;
import entidades.Comentario;
import entidades.Notificacion;
import entidades.Publicacion;
import java.awt.Color;
import java.util.List;
import net.miginfocom.swing.MigLayout;

public class PNotificaciones extends javax.swing.JPanel {

    private NotificacionesBody notiBody;

    public PNotificaciones() {
        initComponents();
    }

    public void init(List<Notificacion> notificaciones) {
        removeAll();
        
        setLayout(new MigLayout("fillx", "5[]5"));
        this.notiBody = new NotificacionesBody(notificaciones);
        add(notiBody, "wrap, width 100%");
        
        refresh();
    }
    
    private void refresh() {
        repaint();
        revalidate();
    }

    public void agregarPublicacion(Notificacion notificacion) {
        notiBody.agregarNotificacion(notificacion);
        refresh();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(233, 233, 233));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
