package components;

import entidades.Usuario;

public class MuroTitle extends javax.swing.JPanel {

    /**
     * Creates new form MuroTitulo
     */
    public MuroTitle(Usuario usuario) {
        initComponents();
        txtSearch.setHintText("¿Qué jashta estás buscando, "+ usuario.getUsuario()+"?");
        lblUsuario.setText(usuario.getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSearch = new swingComponents.JIMSendTextPane();

        setBackground(null);

        lblLogo.setBackground(new java.awt.Color(24, 119, 242));
        lblLogo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(24, 119, 242));
        lblLogo.setText("FACEBOOT");

        lblUsuario.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(24, 119, 242));
        lblUsuario.setText("Jorge");

        jScrollPane1.setViewportView(txtSearch);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLogo)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblUsuario)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogo)
                    .addComponent(lblUsuario))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    private swingComponents.JIMSendTextPane txtSearch;
    // End of variables declaration//GEN-END:variables
}
