package components;

import entidades.Publicacion;
import java.util.List;
import net.miginfocom.swing.MigLayout;
import swingComponents.ScrollBar;

public class MuroBody extends javax.swing.JPanel {

    private List<Publicacion> publicaciones;
    /**
     * Creates new form MuroBody
     */
    public MuroBody(List<Publicacion> publicaciones) {
        initComponents();
        this.publicaciones = publicaciones;
        init();
    }
    
    private void init(){
        panBody.setLayout(new MigLayout("fillx, btt", "", "0[]5"));
        panMuroBody.setVerticalScrollBar(new ScrollBar());
        MuroPublicar muroPub = new MuroPublicar();
        cargarItems();
        panBody.add(muroPub, "wrap, al center");
    }
    
    private void cargarItems(){
        publicaciones.forEach(publi -> {
            MuroPublicacion muroPub = new MuroPublicacion(publi);
            panBody.add(muroPub, "wrap, al center");
            System.out.println("Publicacion: " + publi.getTexto());
        });
        panBody.repaint();
        panBody.revalidate();
    }
    
    public void agregarPublicacion(Publicacion publicacion){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMuroBody = new javax.swing.JScrollPane();
        panBody = new javax.swing.JPanel();

        setBackground(java.awt.Color.white);

        panMuroBody.setBackground(java.awt.Color.white);
        panMuroBody.setBorder(null);
        panMuroBody.setMaximumSize(new java.awt.Dimension(32767, 15000));

        panBody.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout panBodyLayout = new javax.swing.GroupLayout(panBody);
        panBody.setLayout(panBodyLayout);
        panBodyLayout.setHorizontalGroup(
            panBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        panBodyLayout.setVerticalGroup(
            panBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        panMuroBody.setViewportView(panBody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMuroBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMuroBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panBody;
    private javax.swing.JScrollPane panMuroBody;
    // End of variables declaration//GEN-END:variables
}
