package components;

import entidades.Usuario;
import logica.Context;
import guis.FrmEditarUsuario;

public class MuroTitle extends javax.swing.JPanel {
    private Usuario usuario;
    /**
     * Creates new form MuroTitulo
     */
    public MuroTitle() {
        initComponents();
        this.usuario = Context.getInstance().getUsuario();
        txtSearch.setHintText("¿Qué jashta estás buscando?");
        //lblUsuario.setText(usuario.getUsuario());
        btnUser.setText(usuario.getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSearch = new swingComponents.JIMSendTextPane();

        setBackground(null);

        lblLogo.setBackground(new java.awt.Color(24, 119, 242));
        lblLogo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(24, 119, 242));
        lblLogo.setText("FACEBOOT");

        btnUser.setBackground(new java.awt.Color(0, 102, 204));
        btnUser.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUser.setText("ea");
        btnUser.setAlignmentY(1.0F);
        btnUser.setAutoscrolls(true);
        btnUser.setBorder(new javax.swing.border.MatteBorder(null));
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser.setIconTextGap(2);
        btnUser.setPreferredSize(new java.awt.Dimension(16, 20));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtSearch);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLogo)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        new FrmEditarUsuario(usuario).setVisible(true);
    }//GEN-LAST:event_btnUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private swingComponents.JIMSendTextPane txtSearch;
    // End of variables declaration//GEN-END:variables
}
