package components;

import entidades.Publicacion;
import entidades.Usuario;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import logica.Context;
import net.miginfocom.swing.MigLayout;

public class MuroPublicacion extends javax.swing.JPanel {

    private Publicacion publicacion;
    private PublicacionComentarios pubComentarios;

    /**
     * Creates new form MuroPublicacion
     */
    public MuroPublicacion(Publicacion publicacion) {
        initComponents();
        this.publicacion = publicacion;
        init();
    }

    private void init() {
        setLayout(new MigLayout("fillx", "0[fill]0", "0[shrink 0]0[shrink 0]0[shrink]0[shrink 0]0[shrink]0[shrink]0"));
        PublicacionTitle pubTitle = new PublicacionTitle(publicacion);
        PublicacionBody pubBody = new PublicacionBody(publicacion);
        Linea line = new Linea();
        Linea line2 = new Linea();
        PublicacionComentar pubComentar = new PublicacionComentar(publicacion);
        add(pubTitle, "wrap");
        add(pubBody, "wrap");
//        if(publicacion.getComentarios() != null){
//            pubComentarios = new PublicacionComentarios(publicacion);
//            add(line, "wrap");
//            add(pubComentarios, "wrap");            
//        }
        pubComentarios = new PublicacionComentarios(publicacion);
        add(line, "wrap");
        add(pubComentarios, "wrap");
        add(line2, "wrap");
        add(pubComentar, "wrap");
        repaint();
        revalidate();
    }

    public Publicacion getPublicacion() {
        return publicacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(190, 193, 199), 1, true));
        setMaximumSize(new java.awt.Dimension(400, 32767));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
