package components;

import entidades.Hashtag;
import entidades.Usuario;
import logica.Context;
import guis.FrmEditarUsuario;
import guis.FrmNotificaciones;
import interfaces.IFachadaConexion;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;
import logica.FachadaConexion;

public class MuroTitle extends javax.swing.JPanel {
    private Usuario usuario;
    private IFachadaConexion fachadaConexion;
    
    /**
     * Creates new form MuroTitulo
     */
    public MuroTitle() {
        initComponents();
        this.usuario = Context.getInstance().getUsuario();
        this.fachadaConexion = new FachadaConexion();
        
        txtSearch.setHintText("¿Qué jashta estás buscando?");
        
        btnUser.setText(usuario.getUsuario());
        lblLogo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        ImageIcon imageNotis = new ImageIcon("src/main/java/images/notification.png");
        btnNotificaciones.setIcon(new ImageIcon(imageNotis.getImage().getScaledInstance(17, 17, Image.SCALE_DEFAULT)));
        btnNotificaciones.setBorder(null);
        btnNotificaciones.setContentAreaFilled(false);
        
        ImageIcon imageBuscar = new ImageIcon("src/main/java/images/search.png");
        btnBuscar.setIcon(new ImageIcon(imageBuscar.getImage().getScaledInstance(15, 15, Image.SCALE_DEFAULT)));
        btnBuscar.setBorder(null);
        btnBuscar.setContentAreaFilled(false);
        
        ImageIcon imageLogout = new ImageIcon("src/main/java/images/logout.png");
        btnLogOut.setIcon(new ImageIcon(imageLogout.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT)));
        btnLogOut.setBorder(null);
        btnLogOut.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSearch = new swingComponents.JIMSendTextPane();
        btnNotificaciones = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setBackground(null);

        lblLogo.setBackground(new java.awt.Color(24, 119, 242));
        lblLogo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(24, 119, 242));
        lblLogo.setText("FACEBOOT");
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnUser.setBackground(new java.awt.Color(0, 102, 204));
        btnUser.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUser.setText("ea");
        btnUser.setAlignmentY(1.0F);
        btnUser.setAutoscrolls(true);
        btnUser.setBorder(new javax.swing.border.MatteBorder(null));
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser.setIconTextGap(2);
        btnUser.setPreferredSize(new java.awt.Dimension(16, 20));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtSearch);

        btnNotificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionesActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(0, 0, 0));
        btnLogOut.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLogo))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNotificaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        new FrmEditarUsuario(usuario).setVisible(true);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionesActionPerformed
        new FrmNotificaciones().setVisible(true);
    }//GEN-LAST:event_btnNotificacionesActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Hashtag hashtag = new Hashtag(txtSearch.getText());
        fachadaConexion.consultarPublicacionesHashtag(hashtag);
        System.out.println("Se envio 'Consultar por hashtag'");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        fachadaConexion.consultarPublicaciones();
    }//GEN-LAST:event_lblLogoMouseClicked

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
       fachadaConexion.cerrarSesion(usuario);
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNotificaciones;
    private javax.swing.JButton btnUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private swingComponents.JIMSendTextPane txtSearch;
    // End of variables declaration//GEN-END:variables
}
