package components;

import entidades.Comentario;
import java.util.List;
import net.miginfocom.swing.MigLayout;

public class PublicacionComentarios extends javax.swing.JPanel {

    private List<Comentario> comentarios;

    /**
     * Creates new form PublicacionComentarios
     */
    public PublicacionComentarios(List<Comentario> comentarios) {
        initComponents();
        this.comentarios = comentarios;
        init();
    }

    private void init() {
        setLayout(new MigLayout("fillx", "", "5[]5"));
        cargarItems();
    }

    private void crearComentarios() {

    }

    private void cargarItems() {
        comentarios.forEach(comentario -> {
            ComentarioItem comentarioItem = new ComentarioItem();
            comentarioItem.setUsuario(comentario.getUsuario().getUsuario());
            comentarioItem.setComentario(comentario.getTexto());
            add(comentarioItem, "wrap, width 100%");

        });

//        ComentarioItem comentario = new ComentarioItem();
//        comentario.setUsuario("lMahesvara");
//        comentario.setComentario("saqueen pedaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
//        add(comentario, "wrap, width 100%");
//        ComentarioItem comentario2 = new ComentarioItem();
//        comentario2.setUsuario("Nogy");
//        comentario2.setComentario("Saquen amigas");
//        add(comentario2, "wrap, width 100%");
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
